services:
    arturdoruch_simple_rest.exception_listener:
        class: ArturDoruch\SimpleRestBundle\EventListener\ExceptionListener
        arguments: ["%arturdoruch.simple_rest.rest_paths%", "@kernel", "@event_dispatcher"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }